apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:  
  name: allowance-fun-ingress
spec:  
  rules:  
  - host: allowance.fun
    http:  
      paths:  
      - path: "/"
        backend:  
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.html"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.js"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.png"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.json"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.jpg"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.txt"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.map"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/*.ico"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/static/*"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
      - path: "/app/*"
        backend:
          service:
            name: allowance-fun-web-service
            port:
              number: 80
