# This is a basic workflow to help you get started with Actions

name: Build Docker Container

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=allowancedotfun/allowance-fun-web
          VERSION=1.0.0-${GITHUB_RUN_NUMBER}
          echo "::set-output name=tags::${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${VERSION}"
          echo "::set-output name=build_number::BUILD_NUMBER=${GITHUB_RUN_NUMBER}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ${{ steps.prep.outputs.build_number }}
          tags: ${{ steps.prep.outputs.tags }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Update Release
        run: |
          git config user.name "Automated Build"
          git config user.email "jasoncorbett@gmail.com"
          git checkout release
          git merge $GITHUB_SHA
          for orig in *.tmpl; do
            new=`echo $orig |perl -pe 's/\.tmpl$/.yml/'`
            echo "processing $orig into $new";
            cat $orig| perl -pe "s/BUILD_NUMBER/${GITHUB_RUN_NUMBER}/g" >$new
            git add $new
          done
          git commit -m "Updating release to build ${GITHUB_RUN_NUMBER}"
          git push
